
export const throwError = () => {
  throw new Error('Should not have been called');
};
